# Generated by Django 4.2.16 on 2024-11-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=255, unique=True)),
                ('community_id', models.IntegerField(blank=True, null=True)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(default='No title available', max_length=255)),
                ('content', models.TextField(default='No content available')),
                ('score', models.IntegerField(default=0)),
                ('community', models.CharField(default='Unknown', max_length=255)),
                ('creator_name', models.CharField(default='Unknown', max_length=255)),
                ('creator_avatar', models.CharField(default='No avatar available', max_length=255)),
                ('community_description', models.TextField(default='No description available')),
                ('embed_title', models.CharField(default='No embed title available', max_length=255)),
                ('embed_description', models.TextField(default='No embed description available')),
                ('counts_comments', models.IntegerField(default=0)),
                ('counts_score', models.IntegerField(default=0)),
                ('url', models.CharField(default='No URL available', max_length=255)),
                ('article_title', models.CharField(default='No title available', max_length=255)),
                ('article_authors', models.JSONField(default=list)),
                ('publication_date', models.CharField(default='No date available', max_length=255)),
                ('article_content', models.TextField(default='No content available')),
                ('top_image', models.CharField(default='No image available', max_length=255)),
                ('article_keywords', models.JSONField(default=list)),
                ('article_summary', models.TextField(default='No summary available')),
            ],
        ),
    ]
