# Generated by Django 4.2.16 on 2024-11-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='post',
            name='ublication_date',
            field=models.CharField(blank=True, default='No date available', max_length=255, null=True),
        ),
    ]
